version: 2
jobs:
   build:
     docker:
       - image: circleci/node:4.8.4
     steps:
       - checkout
       - run: npm install --quiet
       - run: node_modules/serverless/bin/serverless deploy
